server:
  port: 9090

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/test"
    username: "root"
    password: "123456"

jwt-key:
  jwt-uri: "http://localhost:8080/oauth2/jwks"
  public-key: